language: node_js
node_js:
  - "9.4"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
  - export PATH="$HOME/.yarn/bin:$PATH"
script:
  - npm run build-gh-pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token: $github_token
  on:
    branch: master
