'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var SIGN_IN = exports.SIGN_IN = 'SIGN_IN';
var UPDATE_STREAMS = exports.UPDATE_STREAMS = 'UPDATE_STREAMS';
var UPDATE_MESSAGES = exports.UPDATE_MESSAGES = 'UPDATE_MESSAGES';
var UPDATE_USERS = exports.UPDATE_USERS = 'UPDATE_USERS';
var UPDATE_POINTER = exports.UPDATE_POINTER = 'UPDATE_POINTER';
var UPDATE_CURRENT_MESSAGE = exports.UPDATE_CURRENT_MESSAGE = 'UPDATE_CURRENT_MESSAGE';
var UPDATE_SUBSCRIPTIONS = exports.UPDATE_SUBSCRIPTIONS = 'UPDATE_SUBSCRIPTIONS';