export const SIGN_IN = 'SIGN_IN';
export const UPDATE_STREAMS = 'UPDATE_STREAMS';
export const UPDATE_MESSAGES = 'UPDATE_MESSAGES';
export const UPDATE_USERS = 'UPDATE_USERS';
export const UPDATE_POINTER = 'UPDATE_POINTER';
export const UPDATE_CURRENT_MESSAGE = 'UPDATE_CURRENT_MESSAGE';
export const UPDATE_SUBSCRIPTIONS = 'UPDATE_SUBSCRIPTIONS';
export const ADD_REACTION = 'ADD_REACTION';
